"""rename address

Revision ID: 093e8df64e53
Revises: 5d4cf8365508
Create Date: 2024-01-31 00:15:30.428210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '093e8df64e53'
down_revision = '5d4cf8365508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
